name: Run Unit Tests and Lint Files
on:
  pull_request:
    branches: [ main ]
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    env:
      CI: true
      VITE_OPEN_WEATHER_API_KEY: ${{ secrets.VITE_OPEN_WEATHER_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run test:jest
      - run: npm run lint
